spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myfood
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  pictureGen:
    URL: https://cn.apihz.cn/api/img/apihzimgbaidu.php?id=88888888&key=88888888&limit=10&page=1&words=
# 开启自动驼峰命名映射（column下划线 → property驼峰）
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.rhzhz.mapper: DEBUG # 替换为你的 Mapper 包路径
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG
ai:
  providers:
    openai:
      api-key:
      base-url: https://uu.ci/v1
    deepseek:
      api-key:
      base-url: https://api.deepseek.com/v1
      model: deepseek-chat  # 指定使用 R1 模型
tencent:
  oss:
    SecretKey:
    appid:
    SecretId:
    bucket:
    region:
    URL:
